apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ffmpeg-videos
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: videos
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /videos
    server: 185.137.92.52