apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-videos
spec:
  storageClassName: videos
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-images
spec:
  storageClassName: images
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-viewed
spec:
  storageClassName: viewed
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-most-viewed
spec:
  storageClassName: most-viewed
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-hls
spec:
  storageClassName: hls
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi