apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-viewed
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: viewed
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /viewed
    server: 185.137.92.52