apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-images
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: images
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /media
    server: 185.137.92.52