apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: video-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-server
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75  # Aumenta réplicas se a CPU média ultrapassar 70%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 45  # Aumenta réplicas se a Memória média ultrapassar 80%
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60   # Tempo mínimo antes de reduzir réplicas (padrão: 300s)
      policies:
        - type: Percent
          value: 50   # Reduz no máximo 50% das réplicas de uma vez
          periodSeconds: 30  # Reavalia a cada 30 segundos