apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-video-server-most-viewed
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: most-viewed
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /most-viewed
    server: 185.137.92.52