apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-video-server-hls
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: hls
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /hls
    server: 185.137.92.52