apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-video-server-most-viewed
spec:
  storageClassName: most-viewed
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi