apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-agent
  name: api-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-agent
  template:
    metadata:
      labels:
        app: api-agent
    spec:
      containers:
        - image: guteactestdocker/api-agent:v7
          name: api-agent
          ports:
            - containerPort: 8000